name: BambuStudio-SoftFever

on: [push, pull_request]

jobs:
  appimage-builder:
    name: Linux AppImage Build

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake libgl1-mesa-dev libgtk-3-dev libxkbcommon-dev libunwind-dev libfuse2 -y
      - name: Install dependencies from BuildLinux.sh
        shell: bash
        run: sudo ./BuildLinux.sh -ur
      - name: Fix permissions
        shell: bash
        run: sudo chown $USER -R ./
      - name: Build Bambu Studio dependencies using BuildLinux.sh
        shell: bash
        run: ./BuildLinux.sh -dsr
      - name: Build Bambu Studio AppImage using BuildLinux.sh
        shell: bash
        run: ./BuildLinux.sh -ir
      - uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: './build/BambuStudio_ubu64.AppImage'
